#!/bin/bash
echo -e "
	1] Add
	2] Sub
	3] Mul
	4] Div
read ch
echo "Enter first no.: "
read a
echo "Enter Second no.: "
read b

case $ch in
1)c=$(($a + $b))
echo "Addition: $c";;

2)c=$(($a - $b))
echo "Substraction: $c";;

3)c=$(($a * $b))
echo "Multiplication: $c";;

4)c=$(($a / $b))
echo "Division: $c";;

*)echo "Wrong choice!";;
esac
