#!/bin/bash
echo "Number of arguments: $#"
echo "The arguments are: $*"
echo "The pid is: $$"
echo "The file name: $0"
shift
echo "Number of arguments: $#"
echo "The arguments are: $*"
echo "The pid is: $$"
echo "The file name: $0"
