#!/bin/awk -f
{
	sum=$2+$3+$4
	avg=sum/3
	a[NR]=avg
}
END{
for(i=1;i<=NR;i++)
{
	print a[i]
	total=a[i]+total;
}
all=total/NR
print "AVERAGE:" all
for(j=1;j<=NR;j++)
{
	if(a[j]>all)
	{
		print a[j]
	}
	
}
}
